version: 0.2
env:
  variables:
    APP_NAME: "banking-frontend-angular"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo install process started
      - npm install
  build:
    commands:
      - echo build process started now
      - ng build 
  post_build:
    commands:
      - echo build process finished
      - mv scripts ./dist/banking-frontend-angular
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/banking-frontend-angular