version: 0.2
##sdf
env:
  variables:
    APP_NAME: "banking-frontend-angular"
phases:
  install:
    commands:
      - echo install process started
      - n latest
      - npm install && npm install -g @angular/cli 
  build:
    commands:
      - echo build process started now
      - ng build 
  post_build:
    commands:
      - echo build process finished
      - mv scripts ./dist/banking-frontend-angular
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/banking-frontend-angular