version: 0.2
env:
#zxcvc
  variables:
      CACHE_CONTROL: "86400"
      S3_BUCKET: "{{s3_bucket_url}}"
      BUILD_FOLDER: "dist"

    
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli 
  build:
    commands:
      - echo build process started now
      - ng build 
  post_build:
    commands:
      - echo build process finished
      - mv scripts ./dist/banking-frontend-angular
artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: 'dist*'